
/*Comment*/
export const ADD_COMMIT = 'ADD_COMMIT'
export const DELETE_COMMIT = 'DELETE_COMMIT'
export const EDIT_COMMIT = 'EDIT_COMMIT'

/*cnode */
export const LIST_CNODE_REQUEST = 'LIST_CNODE_REQUEST'
export const LIST_CNODE_REQUEST_FAILURE = 'LIST_CNODE_REQUEST_FAILURE'
export const LIST_CNODE_REQUEST_SUCCESS = 'LIST_CNODE_REQUEST_SUCCESS'